export const quotes = [
    "You have the right to perform your prescribed duties, but you are not entitled to the fruits of your actions.",
    "The soul is neither born, and nor does it die.",
    "Lust, anger and greed are the three gates to self-destructive hell.",
    "Man is made by his belief. As he believes, so he is.",
    "Set your heart upon your work, but never on its reward.",
    "Change is the law of the universe. You can be a millionaire, or a pauper in an instant.",
    "The mind acts like an enemy for those who do not control it.",
    "Perform your obligatory duty, because action is indeed better than inaction.",
    "A person can rise through the efforts of his own mind; or draw himself down, in the same manner.",
    "When meditation is mastered, the mind is unwavering like the flame of a lamp in a windless place.",
    "There is neither this world, nor the world beyond, nor happiness for the one who doubts.",
    "The wise see knowledge and action as one; they see truly.",
    "Pleasure from the senses seems like nectar at first, but it is bitter as poison in the end.",
    "He who has no attachments can truly love others, for his love is pure and divine.",
    "The offering of wisdom is better than any material offering.",
    "One who sees inaction in action, and action in inaction, is intelligent among men.",
    "Reshape yourself through the power of your will; never let yourself be degraded by self-will.",
    "Selfish action imprisons the world. Act selflessly, without any thought of personal profit.",
    "The soul can never be cut to pieces by any weapon, nor burned by fire, nor moistened by water, nor withered by the wind.",
    "A gift is pure when it is given from the heart to the right person at the right time and at the right place, and when we expect nothing in return.",
    "He who is the same to foe and friend, honor and dishonor, cold and heat, pleasure and pain, is dear to Me.",
    "The senses are higher than the body, the mind higher than the senses; above the mind is the intellect, and above the intellect is the Self.",
    "Those who are motivated only by desire for the fruits of action are miserable, for they are constantly anxious about the results of what they do.",
    "Even a little effort toward spiritual awareness will protect you from the greatest fear.",
    "You came empty-handed, and you will leave empty-handed.",
    "The key to happiness is the reduction of desires.",
    "Do everything you have to do, but not with greed, not with ego, not with lust, not with envy but with love, compassion, humility, and devotion.",
    "Death is as sure for that which is born, as birth is for that which is dead. Therefore, grieve not for what is inevitable.",
    "The mind is restless and difficult to restrain, but it is subdued by practice.",
    "There is nothing lost or wasted in this life.",
    "Work for work’s sake, not for yourself. Act but do not be attached to your actions.",
    "The wise man lets go of all results, whether good or bad, and is focused on the action alone.",
    "The immature think that knowledge and action are different, but the wise see them as the same.",
    "The mind is everything. What you think, you become.",
    "Better indeed is knowledge than mechanical practice. Better than knowledge is meditation.",
    "The wise work for the welfare of the world, without thought for themselves.",
    "He who has no attachments can truly love others, for his love is pure and divine.",
    "The offering of wisdom is better than any material offering.",
    "You should perform your duty with a view to guide people and for universal welfare."
  ];
  